### ISSUE TITLE
Where is model_predictions ?

### ISSUE THREAD

**Issue by HarryKane** [blackecho/Deep-Learning-TensorFlow#48]
When I use the method predict,I get a AttributeError
AttributeError: 'DeepBeliefNetwork' object has no attribute 'model_predictions'
any idea?

**Comment by blackecho** [comment]
I've just fixed this with the latest commit, thanks for reporting this issue!
Note that the `predict()` method returns raw class scores. If you then want to compute the accuracy, you'll have to do something like:

    preds = tf.argmax(net.predict(), 1)
    correct = tf.equal(preds, tf.argmax(y, 1))
    accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))

If you just want to compute accuracy I suggest you to use the `score(testX, testY)` method, which does all of the previous for you.

**Comment by nirvana1122** [comment]
Hi, I used pip install to get this package today(May 24), and I still do not see model_predictions. Any idea?
